---
version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-server
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  api:
    container_name: product-api
    ports:
      - "6969:6969"
    build:
      context: .
      dockerfile: Product.API/Dockerfile
    depends_on:
      - broker
      - zookeeper
    environment:
      ASPNETCORE_URLS: http://+:6969
      Kafka:ClientConfigs:BootstrapServers: 'broker:29092'

  product-consumer:
    container_name: product-consumer
    ports:
      - "7171:7171"
    depends_on:
      - broker
      - zookeeper
    build:
      context: .
      dockerfile: Product.Consumer/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:7171
      Kafka:ClientConfigs:BootstrapServers: 'broker:29092'
